DROP TABLE IF EXISTS RECIPES;

CREATE TABLE RECIPES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RECIPENAME VARCHAR(255),
  RECIPETYPE VARCHAR(255),
  SERVINGS INT,
  INGREDIENTS CLOB,
  COOKINGINSTRUCTIONS CLOB, 
  CREATIONDATE DATETIME
);